hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/beauty_salon_CRM
hibernate.connection.username=postgres
hibernate.connection.password=secret
hibernate.show_sql=false
hibernate.hbm2ddl=update