package by.bsuir.tcp;

public enum RequestType {
    LOGIN,
    REGISTER,
    UPDATE_PROFILE,
    DELETE_PROFILE,
    ADD_ORDER,
    GET_ORDERS_BY_USER_ID,
    REJECT_ORDER,
    ROLE_BY_ACCESS_LEVEL,
    GET_ALL_SERVICES,
    GET_MASTER_BY_ID,
    GET_MASTERS_BY_SERVICE_AND_DATE
}
